### PR TITLE
Version Update: Botan 2.11.0

### PR DESCRIPTION
**Pull request by reneme**
This is in response to https://github.com/bincrafters/community/issues/853.

### CODE REVIEW

**Comment by reneme** [comment]
Thanks for fixing the windows linking and compatibility issues.
The latest build failed on macOS Xcode 9 with a build timeout, presumably during `brew update`. :(
Is it possible to rerun just this one platform?  Maybe we should run `brew update —verbose`, so that Travis doesn’t kill us on this long-running and silent command...

Edit: Or maybe use the [Travis Homebrew Integration](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos) to update `brew`, instead of the call in `.ci/install.sh`. I assume that this wouldn't kill the silent update process either.

**Comment by SSE4** [comment]
restarted.
for brew update, please open new PR against the `conan-templates` repository.

**Comment by reneme** [comment]
woohoo! Worked. Can we have this as `stable` then? :)

**Comment by SSE4** [comment]
yes, why not? :)

**Comment by reneme** [comment]
Thank you!

**Pull request merged**
