### PR TITLE
fPIC Stable/2.8.0

### PR DESCRIPTION
**Pull request by Wambou**

### CODE REVIEW

**Comment by Wambou** [comment]
Hi,

I added the fPIC flag so that the library can be compile with it on Linux by default.

I added some pep8 formatting and move "amalgamation" option configuration in "config_option", it made more sens to configure it when the "single_amalgamation" is set in this function.

P.S.: Sorry for the description not being in the main message, I was not writing in the right field and things went south.

**Comment by uilianries** [comment]
Hi @Wambou !

Thanks for your contribution. Let's wait for CI result.

**Comment by Wambou** [comment]
Thank you for your comment.

About your fixup, I will include them in other PR.
I did not understand why you added them but looking at the CI results, I got it.

**Comment by uilianries** [comment]
That's because removed self.options.fPIC on Windows. Thus fPIC will not exist on Windows, raising an error related to invalid option.

**Comment by Wambou** [comment]
Yes I got it but a bit too late.
I fixed it on the 2.7.0 branch and because 2.9.0 is just a version bump, this fix will be included in 2.9.0.

Sorry for not testing it on Windows before submitting...

**Review by SSE4 — APPROVED** [review]

**Pull request merged**
