### PR TITLE
fPIC Stable/2.7.0

### PR DESCRIPTION
**Pull request by Wambou**
Hi,

I backported the fPIC option for 2.7.0, with some pep8 formatting and the config_option for amalgamation.

### CODE REVIEW

**Comment by SSE4** [comment]
@Wambou fails on appveyor:
```
 LINK : fatal error LNK1104: cannot open file 'botand.lib
```

**Comment by Wambou** [comment]
I will try to look at it but the small tests I was able to run on my windows generated the same result as appveyor, with the current stable/2.7.0 branch. I might be missing something somewhere.

**Comment by uilianries** [comment]
Seems like be related to runtime library:

https://ci.appveyor.com/project/BinCrafters/conan-botan/builds/21803769/job/ma34ip90r7v5302s

**Review by SSE4 — APPROVED** [review]

**Comment by uilianries** [comment]
Thanks @SSE4 !

**Pull request merged**
